defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "portfolio" # previously `post` in Jekyll 2.2.
    values:
      layout: "portfolio"
      _comments: 
        image: desktop 1236 x 782
        mobile_image: mobile 419 x 703,5

title: Usecue web development
description: Website development and web hosting
url: https://www.usecue.com
twitter: jhvanderschee
permalink: /blog/:title/

collections:
  portfolio:
    output: true
    permalink: /portfolio/:name/